DataBindingPatterns/Models/Person.cs
namespace DataBindingPatterns.Models
{
    public class Person
    {
        public Person(int personId, string firstName, string lastName, string favoriteFood)
        {
            PersonId = personId;
            FirstName = firstName;
            LastName = lastName;
            FavoriteFood = favoriteFood;
        }

        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FavoriteFood { get; set; }
    }
}

DataBindingPatterns/ViewModels/PersonEditRazorViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DataBindingPatterns.ViewModels
{
    public class PersonEditRazorViewModel
    {
        [Required]
        public int PersonId { get; set; }

        [Required, StringLength(50)]
        public string FirstName { get; set; }

        [Required, StringLength(50)]
        public string LastName { get; set; }

        [Required, StringLength(50)]
        public string FavoriteFood { get; set; }

        // Right away this feels wrong because I am mixing data for a select with model data including validation attributes
        public IEnumerable<SelectListItem> Foods { get; set; } 
    }
}

DataBindingPatterns/ViewModels/PersonViewModel.cs
namespace DataBindingPatterns.ViewModels
{
    public class PersonViewModel
    {
        public int PersonId { get; set; }
        public string FullName { get; set; }
        public string FavoriteFood { get; set; }
    }
}

DataBindingPatterns/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataBindingPatterns.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

DataBindingPatterns/Controllers/People1Controller.cs
using System;
using System.Linq;
using System.Web.Mvc;
using DataBindingPatterns.ViewModels;

namespace DataBindingPatterns.Controllers
{
    // straight razor
    public class People1Controller : PeopleController
    {

        [HttpGet]
        public ActionResult Index()
        {
            var vm = GetPersonViewModels();
            return View(vm);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var vm = GetPeople()
                .Where(x => x.PersonId == id)
                .Select(x => new PersonEditRazorViewModel()
                {
                    PersonId = x.PersonId,
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    FavoriteFood = x.FavoriteFood
                }).SingleOrDefault();

            if (vm == null)
            {
                return HttpNotFound();
            }

            SetFoodList(vm);

            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(PersonEditRazorViewModel vm)
        {
            var food = GetFood();
            if (!food.Contains(vm.FavoriteFood))
            {
                var msg = string.Format("'{0}' is not in the list '{1}'.", vm.FavoriteFood, string.Join(", ", food));
                ModelState.AddModelError("Favorite Food", msg);
            }

            // Have to rebuild select list if validation or update fails
            if (!ModelState.IsValid)
            {
                SetFoodList(vm);
                return View("Edit", vm);
            }

            try
            {
                // update
            }
            catch (Exception)
            {
                // rebuild select list and redirect to edit (if appropriate)
                throw;
            }

            return RedirectToAction("Index");
        }

        private void SetFoodList(PersonEditRazorViewModel vm)
        {
            var foods = GetFood().ToList();

            // add existing favorite if not in list
            if (!foods.Contains(vm.FavoriteFood))
            {
                foods.Add(vm.FavoriteFood);
            }

            vm.Foods = foods.Select(x => new SelectListItem()
            {
                Text = x,
                Value = x,
                Selected = (x == vm.FavoriteFood)
            });
        }

    }
}

DataBindingPatterns/Controllers/People3Controller.cs
using System.Web.Mvc;

namespace DataBindingPatterns.Controllers
{
    public class People3Controller : PeopleController
    {

        public ActionResult Index()
        {
            var vm = GetPersonViewModels();
            return View(vm);
        }
    }
}

DataBindingPatterns/Controllers/PeopleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DataBindingPatterns.Models;
using DataBindingPatterns.ViewModels;

namespace DataBindingPatterns.Controllers
{
    public abstract class PeopleController : Controller
    {
        protected IEnumerable<Person> GetPeople()
        {
            return new List<Person>
            {
                new Person(1, "Alexander", "Hamilton", "Boeuf a la mode"),
                new Person(2, "Amadeus", "Mozart", "Faschingkrapfen"),
                new Person(3, "Marco", "Polo", "Martarolo"),
                new Person(4, "Helen", "Keller", "French fries")
            };
        }

        protected IEnumerable<string> GetFood()
        {
            return new[] { "Cheeseburger", "Roast chicken", "Veggie stir fry" };
        }

        protected   IEnumerable<PersonViewModel> GetPersonViewModels()
        {
            return GetPeople()
                .Select(x => new PersonViewModel()
                {
                    PersonId = x.PersonId,
                    FullName = x.FirstName + " " + x.LastName,
                    FavoriteFood = x.FavoriteFood
                });
        }

        protected PersonViewModel GetPersonViewModel(int id)
        {
            return GetPeople()
                .Where(x => x.PersonId == id)
                .Select(x => new PersonViewModel()
                {
                    PersonId = x.PersonId,
                    FullName = x.FirstName + " " + x.LastName,
                    FavoriteFood = x.FavoriteFood
                }).SingleOrDefault();
        }

    }
}

DataBindingPatterns/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<ul class="nav nav-pills">
    <li>
        <a href="@Url.Action("Index", "People1")">Straight Razor</a>
        <a href="@Url.Action("Index", "People3")">Knockout</a>
    </li>
</ul>

DataBindingPatterns/Views/People1/Edit.cshtml
@model DataBindingPatterns.ViewModels.PersonEditRazorViewModel

@{
    ViewBag.Title = "Edit";
}

<h1>Edit</h1>


<p>
    Notes
    <ul>
        <li>There are a numerous methods for creating the editor template.</li>
        <li>Have to use hidden field or other means for disabled controls.</li>
    </ul>
</p>

@using (@Html.BeginForm())
{
    <div class="alert alert-warning">
        @Html.ValidationSummary("Errors")
    </div>

    <div class="form-group">
        <label>ID</label>
        @Html.HiddenFor(x => x.PersonId)
        @Html.TextBoxFor(x => x.PersonId, new { @class = "form-control", disabled = "disabled" })
    </div>

    <div class="form-group">
        <label>First Name</label>
        @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Last Name</label>
        @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Favorite Food</label>
        @Html.DropDownListFor(x => x.FavoriteFood, Model.Foods, new { @class = "form-control"})
    </div>

    <input type="submit" value="Submit" />
}

DataBindingPatterns/Views/People1/Index.cshtml
@model IEnumerable<DataBindingPatterns.ViewModels.PersonViewModel>

@{
    ViewBag.Title = "People - Razor";
}

<h1>People - Razor</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Favorite Food</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var person in Model)
        {
            <tr>
                <td><a href="@Url.Action("Edit", new { id = person.PersonId})" class="btn btn-default">Edit</a></td>
                <td>@person.FullName</td>
                <td>@person.FavoriteFood</td>
            </tr>
        }
    </tbody>
</table>

DataBindingPatterns/Views/People3/Index.cshtml
@model IEnumerable<DataBindingPatterns.ViewModels.PersonViewModel>

@{
    ViewBag.Title = "People - Knockout";
}

@section scripts
{
    <script>
        var ns = ns || {};

        ns.index = (function() {

            var ViewModel = function(people) {
                this.people = ko.observableArray(people);
            }

            var vm;

            return {
                init: function(people) {
                    vm = new ViewModel(people);
                    ko.applyBindings(vm);
                }
            }
        })();

        $(document).ready(function() {
            var people = @Html.Raw(Json.Encode(Model));
            ns.index.init(people);
        });

    </script>
}

<h1>People Knockout</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Favorite Food</th>
        </tr>
    </thead>
    <tbody data-bind="foreach: people">
        <tr>
            <td data-bind="text: FullName"></td>
            <td data-bind="text: FavoriteFood"></td>
        </tr>
    </tbody>
</table>

DataBindingPatterns/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)
</body>
</html>